# Generated by Django 4.2.16 on 2024-11-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_order_remove_customer_purchase_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
